#server:
#  port: 433
#  ssl:
#    key-store: classpath:mjj.pfx
#    key-store-password: 8M8BUCn8
#    key-store-type: PKCS12


server:
  port: 443
  ssl:
    key-store: classpath:local.pfx
    key-store-password: mjjchou123
    key-store-type: PKCS12



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wx_reminds?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true


wx:
  appId: wxdfabd93da15630ec
  appSecret: f45c0991a1a4371e5798c47d23ca2f6f





